# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-05-18 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('valueaccounting', '0014_location_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=b'photos', verbose_name='photo')),
                ('photo_url', models.CharField(blank=True, max_length=255, verbose_name='photo url')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_pictures', to='valueaccounting.EconomicResource', verbose_name='resource')),
            ],
        ),
    ]
